controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

listofbooks:
    path: /booklist/{page}
    controller: App\Controller\BookBinderController::renderBookList

book:
    path: /book/{id}
    controller: App\Controller\BookBinderController::renderBook

myprofile:
    path: /myprofile
    controller: App\Controller\BookBinderController::renderMyProfile

person:
    path: /person/{id}
    controller: App\Controller\BookBinderController::renderPeople

usersettings:
    path: /usersettings
    controller: App\Controller\BookBinderController::renderUserSettings

home:
    path: /home
    controller: App\Controller\BookBinderController::renderHomepage

register:
    path: /register
    controller: App\Controller\BookBinderController::renderRegister

search:
    path: /booklist/search/{searchTerm}
    controller: App\Controller\BookBinderController::renderBookListSearch

login:
    path: /login
    controller: App\Controller\LoginController::index

app_logout:
    path: /logout
    methods: GET

searchpeople:
    path: /peoplelist/search/{searchTerm}
    controller: App\Controller\BookBinderController::renderPeopleListSearch

listofpeople:
    path: /peoplelist/{page}
    controller: App\Controller\BookBinderController::renderPeopleList
