controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /booklist
    controller: App\Controller\BookBinderController::renderBookList

book:
    path: /book
    controller: App\Controller\BookBinderController::renderBook

person:
    path: /person
    controller: App\Controller\BookBinderController::renderPerson