controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

listofbooks:
    path: /booklist/{page}
    controller: App\Controller\BookController::renderBookList

book:
    path: /book/{id}
    controller: App\Controller\BookController::renderBook

myprofile:
    path: /myprofile
    controller: App\Controller\ProfileController::renderMyProfile

person:
    path: /person/{id}
    controller: App\Controller\PeopleController::renderPeople

usersettings:
    path: /usersettings
    controller: App\Controller\ProfileController::renderUserSettings

home:
    path: /home
    controller: App\Controller\BookBinderController::renderHomepage

register:
    path: /register
    controller: App\Controller\RegistrationController::register

search:
    path: /booklist/search/{searchTerm}
    controller: App\Controller\BookController::renderBookListSearch

login:
    path: /login
    controller: App\Controller\LoginController::index

app_logout:
    path: /logout
    methods: GET

searchpeople:
    path: /peoplelist/search/{searchTerm}
    controller: App\Controller\PeopleController::renderPeopleListSearch

listofpeople:
    path: /peoplelist/{page}
    controller: App\Controller\PeopleController::renderPeopleList

searchlibraries:
    path: /librarylist/search/{searchTerm}
    controller: App\Controller\LibraryController::renderLibraryListSearch

listoflibraries:
    path: /librarylist/{page}
    controller: App\Controller\LibraryController::renderLibraryList
